name: motivation
description: A Flutter app for uploading study videos
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  permission_handler: ^11.1.0
  video_player: ^2.8.2
  camera: ^0.10.5+9
  http: ^1.1.2
  path_provider: ^2.1.1
  path: ^1.8.3
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

